### ISSUE TITLE
Probe: ptrace on Linux

### ISSUE THREAD

**Issue by goodhoko** [tonarino/acoustic_profiler#7]
Explore implementing a probe using ptrace to hook into some process' syscalls

**Comment by PabloMansanet** [comment]
Interesting resources:

* https://nullprogram.com/blog/2018/06/23/
* https://nullprogram.com/blog/2018/01/17/ (about dtrace, but seems like a good read too anyway)

**Comment by PabloMansanet** [comment]
The first of the links above does a line-by-line of what's probably the simplest probe we could implement on `ptrace`, a simplified `strace`. I think we can definitely go with that one. There's some architecture-specific register reads that would restrict us to x86 and Linux, but it should be good as a start.

I'm going to make a prototype Rust clone of that snippet using the `ptrace` bindings of the `nix` crate.

**Comment by goodhoko** [comment]
Another good resource could be this https://www.cyphar.com/blog/post/20160703-remainroot-ptrace-hell

**Comment by goodhoko** [comment]
Done in #23
